[workspace]
changelog_update = true
changelog_path = "CHANGELOG.md"

git_tag_enable = true
git_tag_name = "v{{ version }}"

git_release_enable = true
git_release_draft = false

semver_check = true

[[package]]
name = "tincan"
changelog_include = [ "feat", "fix", "perf", "refactor" ]
